### ISSUE TITLE
Parse Markdown in posts and comments

### ISSUE THREAD

**Issue by isiah-lloyd** [ekarbe/reddit-viewer#20]
It would be nice if we could parse the markdown of self-posts and comments. There are multiple ways this could be done.

1. Use a third-party markdown parser such as https://github.com/markdown-it/markdown-it
2. Use the `selftext_html` property on the post and comment object. 

I attempted doing the second option thinking that it would be as simple as replacing templates.js#L423 with `data.selftext_html` but it just inserted the html as a string. I also do not know if there is security concerns with the second option.

**Comment by ekarbe** [comment]
@isiah-lloyd I think the the html prop needs to be decoded before using it in the code. 

It's set like this: `selftext_html:"&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Lorem ipsum&lt;/p&gt;
&lt;/div&gt;&lt;!-- SC_ON --&gt;"` and gets automatically decoded by the html window of vscode which results in showing the html text.

There is probably a js native decode function available.

**Comment by ekarbe** [comment]
Will be available in 2.0.0 which should be available in about 1 to 2 weeks hopefully.

Edit: Or nah

**Comment by ekarbe** [comment]
Oh and I got this working with the `raw_json=1` param in the api which returns unencoded values
