### ISSUE TITLE
 can't login with my accout recently

### ISSUE THREAD

**Issue by YukiSou** [ekarbe/reddit-viewer#40]
### Description

can't login with my accout recently

### Steps to Reproduce

just login

### Versions

Code 1.43.2

### Additional Information

I have a proxy setting with the Code, but I'm sure I can login with the same setting several days ago.

**Comment by ekarbe** [comment]
There have been some changes to the cookies.
So you could/can login but the session is invalid and it seems that you are not logged in.

I could fix the session check, but it seems that there are some more issues so that the own frontpage cannot be fetched. I will look into it at some later point.

**Comment by YukiSou** [comment]
Looks like the vscode group has fix the cookie issue, now I can login normally

**Comment by ekarbe** [comment]
@YukiSou confirmed. But I think it's a change on Reddits end and not in VSCode.
Either way it works again.
